### ISSUE TITLE
array.ps1

### ISSUE THREAD

**Issue by ghostsquad** [KirkMunro/TypePx#2]
https://github.com/KirkMunro/TypePx/blob/master/typedata/array.ps1#L136

```Powershell
if ($results.Count -eq 1) {
    ,$results
} else {
    $results
}
```

Shouldn't this be `$results.Count -le 1` ?

```Powershell
#### Repro

PS> function return0    { $o = new-object System.Collections.ArrayList; if($o.Count -eq 1) {return ,$o} else {return $o} }
PS> function return0alt { $o = new-object System.Collections.ArrayList; if($o.Count -le 1) {return ,$o} else {return $o} }
PS> function return1    { $o = new-object System.Collections.ArrayList; [Void]$o.Add('a'); if($o.Count -eq 1) {return ,$o} else {return $o} }
PS> function return2    { $o = new-object System.Collections.ArrayList; [Void]$o.Add('a'); [Void]$o.Add('b'); if($o.Count -eq 1) {return ,$o} else {return $o} }

#### Results

PS> $result = return0; $result.GetType(); $result.Count;
You cannot call a method on a null-valued expression.
At line:1 char:20
+ $result = return0; $result.GetType(); $result.Count;
+                    ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

0

PS> $result = return0alt; $result.GetType().ToString(); $result.Count;
System.Collections.ArrayList
0

PS> $result = return1; $result.GetType(); $result.Count;
System.Collections.ArrayList
1

PS> $result = return2; $result.GetType().ToString(); $result.Count;
System.Object[]
2
```

**Comment by KirkMunro** [comment]
The current design follows how PowerShell cmdlets work, returning something if there is something to return, or nothing if there are no results. I suppose you could argue that since this is a method, it should always return what it was designed to return, in which case no slices would be identified by the return of an empty collection.  I'm still thinking about this.

**Comment by KirkMunro** [comment]
Ok, after reflecting on this a bit, I decided to make it always return something, so if you have an empty array and you try to slice it, you'll get back an empty array (e.g. no slices).  Thanks for the suggestion.  I'll publish this to the master branch in GitHub shortly and include this in the next release (not sure when that will be yet).
